# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Solar Options Project
author: Naoki Conning
logo: logo.jpg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  exclude_patterns: []  
  
only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

launch_buttons:
  colab_url: "https://colab.research.google.com"
  thebe: true

# Information about where the book exists on the web
repository:
  url: https://github.com/naokic3/solar_projectN  # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)
  
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - dollarmath
    - linkify

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true

only_build_toc_files: true

